gmail:
  enabled: true
  count: 10
  plus: true
  dot_variation: true
  plus_dot_combination: true  # Mix of both

outlook:
  enabled: true
  count: 5
  plus: true
  dot: false  # Ensure Outlook does not use dots
